# Generated by Django 3.2.5 on 2021-07-24 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_productcategory_href'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcategory',
            name='href',
        ),
    ]
